### ISSUE TITLE
Can not login with Github anymore

### ISSUE THREAD

**Issue by at-anhuibl** [taylorotwell/zendcon-app#1]
Github return 404 error. :)

**Comment by cnxh** [comment]
you need to set these constants in your .env file first:

GITHUB_KEY=xxxx
GITHUB_SECRET=xxxx
GITHUB_REDIRECT=http://xxxxx

**Comment by at-anhuibl** [comment]
@cnxh 
I am sorry for my poor knownledge.
Thank you very much.
